name: 'Reportly'
description: 'Turn test results into useful reports'
inputs:
  test_results_pattern:
    description: 'Directory that contains raw test results'
    required: true
    default: '/reportly/test-reports/**/*.xml'
outputs:
  report:
    description: 'A useful report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /reportly/entrypoint.sh
  args:
    - ${{ inputs.test_results_pattern }}
