name: 'Reportly'
description: 'Turn test results into useful reports'
inputs:
  title:
    description: 'The report title'
    required: true
    default: "${{ github.repository }} test report"
  test_reports_pattern:
    description: 'Directory that contains raw test results'
    required: true
    default: '["./test-reports/unit-tests/*.xml", "./test-reports/integration-tests/*.xml"]'
  include_skipped:
    description: "Whether to include skipped tests in the report"
    default: false
  include_passed:
    description: "Whether to include passed tests in the report"
    default: false
outputs:
  report:
    description: 'A useful report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /reportly/entrypoint.sh
  args:
    - --include-skipped 
    - "${{ inputs.include_skipped}}"
    - --include-passed
    - "${{ inputs.include_passed}}"
    - --report-title
    - "${{ inputs.title }}"
    - --test-reports-pattern
    - "/github/workspace/${{ fromJSON(inputs.test_reports_pattern)}}"


