name: 'Reportly'
description: 'Turn test results into useful reports'
inputs:
  report_title:
    description: 'The report title'
    required: true
    default: "My simple test report"
  test_reports_pattern:
    description: 'Directory that contains raw test results'
    required: true
    default: "./test-reports/**/*.xml"
outputs:
  report:
    description: 'A useful report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /reportly/entrypoint.sh
  args:
    - ${{ inputs.report_title }}
    - "/reportly/${{ inputs.test_reports_pattern }}"
