name: 'testvox'
description: 'Turn test results into useful reports'
inputs:
  title:
    description: 'The report title'
    required: true
    default: "${{ github.repository }} test report"
  reports_pattern:
    description: 'Directory that contains raw test results'
    required: true
    default: "./build/test-results/*.xml"
  include_skipped:
    description: "Whether to include skipped tests in the report"
    default: false
  include_passed:
    description: "Whether to include passed tests in the report"
    default: false
outputs:
  report:
    description: 'A human readable test report'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /testvox/entrypoint.sh
  args:
    - "${{ inputs.include_skipped}}"
    - "${{ inputs.include_passed}}"
    - "${{ inputs.title }}"
    - "/github/workspace/${{inputs.reports_pattern}}"


