on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: generate_report
      - name: Get the output
        run: |
          echo "The generated report is: ${{ steps.generate_report.outputs.report }}"
