on: [push]

jobs:
  create_slack_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        id: generate_report_default
      - name: Send default test report
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: ${{steps.generate_report_default.outputs.report}}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - uses: ./ # Uses an action in the root directory
        id: generate_report_custom_test_results_pattern
        with:
          test_results_pattern: "/reportly/test-reports/unit-tests/*.xml"
      - name: Send integration test report
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: ${{steps.generate_report_custom_test_results_pattern.outputs.report}}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      
      
