name: Workflow on branch, excluding main

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  build_lint_test:
    uses: ./.github/workflows/build-lint-test.yml
    with:
      checkout_ref: ${{ github.ref }}
  check_crate_version_availability:
    uses: ./.github/workflows/check-crate-version-availability.yml
    with:
      checkout_ref: ${{ github.ref }}
  #TODO: move    
  release:
    name: Release project on crates.io, Docker and on Github
    runs-on: ubuntu-latest
    #TODO: review dependencies
    steps:
      - name: Install Just
        run: sudo snap install --edge --classic just
      - uses: actions/checkout@v4
      - name: "Get project version"
        id: get_project_version
        run: |
          crate_version=$(just get-project-version)
          echo "VERSION=$crate_version" >> $GITHUB_OUTPUT
      - name: "Publishing..."
        run: "I'm publishing version: ${{ steps.get_project_version.outputs.VERSION }}"