name: Workflow on branch, excluding main

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  build-lint-test:
    uses: ./.github/workflows/build-lint-test.yml
    with:
      checkout_ref: ${{ github.ref }}
  check-crate-version-availability:
    uses: ./.github/workflows/check-crate-version-availability.yml
    with:
      checkout_ref: ${{ github.ref }}