name: Workflow on branch, excluding main

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  build_lint_test:
    uses: ./.github/workflows/build-lint-test.yml
    with:
      checkout_ref: ${{ github.ref }}
  check_crate_version_availability:
    uses: ./.github/workflows/check-crate-version-availability.yml
    with:
      checkout_ref: ${{ github.ref }}
  #TODO: move    
  release:
    name: Release project on crates.io, Docker and on Github
    runs-on: ubuntu-latest
    #TODO: review dependencies
    needs: check_crate_version_availability
    steps:
      - uses: actions/checkout@v4
      - name: "publishing..."
        run: |
          echo "I'm publishing version ${{needs.check_crate_version_availability.outputs.version}}"