name: Build, Test, Format

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  build-test-coverage:
    uses: ./.github/workflows/build-format-test.yml
    with:
      checkout_ref: ${{ github.ref }}
  check-crate-version-available:
    # needs: build-test-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Just
        run: sudo snap install --edge --classic just
      - uses: actions/checkout@v4
      - name: Get current project version from Cargo.toml
        run: echo "CRATE_VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version'" >> $GITHUB_ENV
      - name: Check if crate version is available
        shell: bash
        run: just check-crate-version-available $CRATE_VERSION