name: Workflow on branch, excluding main

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  build_lint_test:
    uses: ./.github/workflows/build-lint-test.yml
    with:
      checkout_ref: ${{ github.ref }}
  check_crate_version_availability:
    uses: ./.github/workflows/check-crate-version-availability.yml
    with:
      checkout_ref: ${{ github.ref }}
  #TODO: move    
  release-docker:
    name: Release project on crates.io, Docker and on Github
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    #TODO: review dependencies
    steps:
      - name: Install Just
        run: sudo snap install --edge --classic just
      - uses: actions/checkout@v4
      - name: "Get project version"
        id: get_project_version
        run: |
          crate_version=$(just get-project-version)
          echo "VERSION=$crate_version" >> $GITHUB_OUTPUT
      # TODO: remove
      - name: "Publishing..."
        run: echo ${{ steps.get_project_version.outputs.VERSION }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: adilisio/testvox:${{ steps.get_project_version.outputs.VERSION }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/adilisio/testvox
          subject-digest: ${{ steps.push.outputs.digest }}